### ISSUE TITLE
musl 1.1.11 doesn't handle SECTION symbol type

### ISSUE THREAD

**Issue by cdotstout** [effenel/toolchain#4]
This results in dlopen failing when mojo_shell attempts to load spinning_cube.mojo.

Small patch (attached) from upstream musl seems to fix the issue.

[musl-dlopen.patch.txt](https://github.com/effenel/toolchain/files/16447/musl-dlopen.patch.txt)

**Comment by kulakowski** [comment]
Will update to 1.1.12 to get the fix.

**Comment by cdotstout** [comment]
Kind of amazing that 1.1.12 was released a few hours after I filed this bug
:)

I had tried testing against top of tree musl but found that init crashed
during startup. Hopefully the cause of that isn't part of 1.1.12.  Maybe I
was doing something wrong, though I tried that approach more than once with
the same result.

**Comment by kulakowski** [comment]
Any context into the crash?

**Comment by cdotstout** [comment]
No, the kernel panic'd after the crash :)

In any case, it appears all is well with 1.1.12.

**Comment by shinykitten** [comment]
FWIW I just did a full clean build from ToT (checked out about 30 minutes ago, includes musl 1.1.12) and everything boots fine.
